# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Penrose Trip
email: davidpaipa03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is an interactive portal for informative use,
  which seeks to open a space for the juxtaposition between psychedelia, science, programming and art.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://penrosetrip.com" # the base hostname & protocol for your site
twitter_username: PenroseTrip
github_username:  PaipaPsyche

# Build settings
markdown: kramdown
